export const posts = [
    {
        id: "1",
        title: "Understanding React Native",
        content: "React Native lets you build mobile apps using JavaScript and a single codebase for Android and iOS...",
        author: "Aritra",
        date: "Feb 12, 2026",
    },
    {
        id: "2",
        title: "Why Clean UI Matters",
        content: "A clean interface improves readability, builds trust, and keeps users focused on content...",
        author: "Aritra",
        date: "Feb 10, 2026",
    },
    {
        id: "3",
        title: "Building a Blog App with Expo Router",
        content: "Expo Router simplifies navigation in React Native using file-based routing...",
        author: "Aritra",
        date: "Feb 8, 2026",
    },
    {
        id: "4",
        title: "State Management in React Native",
        content: "Managing state efficiently is key to building scalable and maintainable apps...",
        author: "Aritra",
        date: "Feb 5, 2026",
    },
    {
        id: "5",
        title: "Designing for Mobile First",
        content: "Mobile-first design ensures better usability and performance across devices...",
        author: "Aritra",
        date: "Feb 3, 2026",
    },
    {
        id: "6",
        title: "Improving App Performance",
        content: "Optimizing FlatList, reducing re-renders, and managing memory can dramatically improve performance...",
        author: "Aritra",
        date: "Jan 30, 2026",
    },
    {
        id: "7",
        title: "Authentication Flow in Expo Apps",
        content: "Implementing secure login flows using context and protected routes...",
        author: "Aritra",
        date: "Jan 28, 2026",
    },
    {
        id: "8",
        title: "Reusable Components in React Native",
        content: "Building reusable UI components makes your codebase cleaner and easier to maintain...",
        author: "Aritra",
        date: "Jan 25, 2026",
    },
    {
        id: "9",
        title: "Styling with NativeWind",
        content: "NativeWind brings Tailwind-style utility classes to React Native...",
        author: "Aritra",
        date: "Jan 22, 2026",
    },
    {
        id: "10",
        title: "From Idea to Deployment",
        content: "Turning a simple idea into a production-ready mobile app requires planning and iteration...",
        author: "Aritra",
        date: "Jan 20, 2026",
    },
];